; This file is used to specify the default values for editor settings
; These are set for new users but individuals can override that in the editor settings UI

; Enable the plugins and favorites to be displayed by default
[/Script/UnrealEd.ContentBrowserSettings]
DisplayPluginFolders=True
DisplayFavorites=True

[ContentBrowser]
FavoritePaths=/OrionGame/Content,/OrionGameTemplate
; Make all the content browsers have the Favorites expanded too
ContentBrowserTab1.FavoritesAreaExpanded=True
ContentBrowserTab2.FavoritesAreaExpanded=True
ContentBrowserTab3.FavoritesAreaExpanded=True
ContentBrowserTab4.FavoritesAreaExpanded=True
ContentBrowserDrawer.FavoritesAreaExpanded=True

[/Script/ModelContextProtocolEngine.ModelContextProtocolSettings]
ServerUrlPath=/mcp
ServerPortNumber=18765
bAutoStartServer=True
bEnableToolSearch=True

; Some commonly used editor maps that will be displayed in the editor task bar
[/Script/CommonEditor.CommonEditorDeveloperSettings]
+CommonEditorMaps=/Game/System/Frontend/Maps/L_Frontend.L_Frontend
+CommonEditorMaps=/OrionGameTemplate/Maps/L_OrionGameTemplateDemo.L_OrionGameTemplateDemo
